/**
 * Default theme — runtime menu loader.
 *
 * Contract:
 *   - The HTML rendered by `BaseLayout` includes empty containers
 *     marked with `data-cms-menu="header"` (or "footer"), each holding a
 *     `<ul>` element.
 *   - This script fetches `/menu.json` (regenerated by the admin every
 *     time menus, posts or terms change) and fills in the lists.
 *   - The burger toggle button is wired up to flip `aria-expanded` and
 *     show / hide the `#burger-menu` overlay via a `.is-open` class.
 *
 * Failure mode is silent on purpose: if the fetch fails (network down,
 * 404 because Flexweg hasn't received the first publish yet), the
 * containers stay empty. The user sees no menu rather than a panic-y
 * error, and the admin's logs/toasts surface the underlying issue.
 */
(function () {
  "use strict";

  function fetchMenu() {
    // Cache-busting via Date.now would invalidate Flexweg's CDN headers
    // for everyone — we instead rely on the browser's HTTP cache and
    // the user can hard-refresh if they updated the menu mid-session.
    return fetch("/menu.json", { credentials: "omit" })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .catch(function (err) {
        console.warn("[cms] menu.json load failed:", err);
        return null;
      });
  }

  function renderItem(item) {
    var li = document.createElement("li");
    var a = document.createElement("a");
    a.href = item.href || "#";
    a.textContent = item.label || "";
    if (samePath(a.href)) {
      a.setAttribute("aria-current", "page");
    }
    li.appendChild(a);
    if (item.children && item.children.length) {
      var sub = document.createElement("ul");
      sub.className = "menu-children";
      item.children.forEach(function (child) {
        sub.appendChild(renderItem(child));
      });
      li.appendChild(sub);
    }
    return li;
  }

  // Compares the link's path against the current location, normalising
  // trailing slashes and the implicit /index.html so /news/ matches a
  // link pointing to /news/index.html (and vice versa).
  function samePath(href) {
    try {
      var url = new URL(href, window.location.origin);
      var here = window.location.pathname.replace(/\/index\.html$/, "/");
      var there = url.pathname.replace(/\/index\.html$/, "/");
      return here === there;
    } catch (e) {
      return false;
    }
  }

  function paint(menu) {
    if (!menu) return;
    document.querySelectorAll("[data-cms-menu]").forEach(function (host) {
      var key = host.getAttribute("data-cms-menu");
      var items = (menu && menu[key]) || [];
      var list = host.querySelector("ul");
      if (!list) return;
      list.innerHTML = "";
      items.forEach(function (item) {
        list.appendChild(renderItem(item));
      });
      // Hide the host until we have content — keeps the layout from
      // reserving empty space when there's no menu configured.
      if (items.length === 0) {
        host.setAttribute("hidden", "");
      } else {
        host.removeAttribute("hidden");
      }
    });
  }

  function wireBurger() {
    var toggle = document.querySelector(".burger-toggle");
    var menu = document.getElementById("burger-menu");
    if (!toggle || !menu) return;
    function setOpen(open) {
      toggle.setAttribute("aria-expanded", open ? "true" : "false");
      menu.classList.toggle("is-open", open);
      document.body.classList.toggle("burger-open", open);
    }
    toggle.addEventListener("click", function () {
      var isOpen = toggle.getAttribute("aria-expanded") === "true";
      setOpen(!isOpen);
    });
    // Close on Escape and on link click — convenient on mobile.
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") setOpen(false);
    });
    menu.addEventListener("click", function (e) {
      if (e.target.tagName === "A") setOpen(false);
    });
  }

  function ready(fn) {
    if (document.readyState !== "loading") fn();
    else document.addEventListener("DOMContentLoaded", fn);
  }

  ready(function () {
    wireBurger();
    fetchMenu().then(paint);
  });
})();
