/**
 * Default theme — runtime menu loader.
 *
 * Contract:
 *   - The HTML rendered by `BaseLayout` includes empty containers
 *     marked with `data-cms-menu="header"` (or "footer"), each holding a
 *     `<ul>` element.
 *   - This script fetches `/data/menu.json` (regenerated by the admin
 *     every time menus, posts or terms change) and fills in the lists.
 *   - The burger toggle button is wired up to flip `aria-expanded` and
 *     show / hide the `#burger-menu` overlay via a `.is-open` class.
 *   - The script ALSO injects a close button into `#burger-menu` and
 *     wires an outside-click handler — neither requires HTML changes
 *     so adding them doesn't force a full site republish.
 *
 * Failure mode is silent on purpose: if the fetch fails (network down,
 * 404 because Flexweg hasn't received the first publish yet), the
 * containers stay empty. The user sees no menu rather than a panic-y
 * error, and the admin's logs/toasts surface the underlying issue.
 */
(function () {
  "use strict";

  function fetchMenu() {
    // Cache-busting via Date.now would invalidate Flexweg's CDN headers
    // for everyone — we instead rely on the browser's HTTP cache and
    // the user can hard-refresh if they updated the menu mid-session.
    // Path is `/data/menu.json` (grouped with other content snapshots
    // to keep the site root uncluttered).
    return fetch("/data/menu.json", { credentials: "omit" })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .catch(function (err) {
        console.warn("[cms] menu.json load failed:", err);
        return null;
      });
  }

  function renderItem(item) {
    var li = document.createElement("li");
    var a = document.createElement("a");
    a.href = item.href || "#";
    a.textContent = item.label || "";
    if (samePath(a.href)) {
      a.setAttribute("aria-current", "page");
    }
    li.appendChild(a);
    if (item.children && item.children.length) {
      var sub = document.createElement("ul");
      sub.className = "menu-children";
      item.children.forEach(function (child) {
        sub.appendChild(renderItem(child));
      });
      li.appendChild(sub);
    }
    return li;
  }

  // Compares the link's path against the current location, normalising
  // trailing slashes and the implicit /index.html so /news/ matches a
  // link pointing to /news/index.html (and vice versa).
  function samePath(href) {
    try {
      var url = new URL(href, window.location.origin);
      var here = window.location.pathname.replace(/\/index\.html$/, "/");
      var there = url.pathname.replace(/\/index\.html$/, "/");
      return here === there;
    } catch (e) {
      return false;
    }
  }

  function paint(menu) {
    if (!menu) return;
    document.querySelectorAll("[data-cms-menu]").forEach(function (host) {
      var key = host.getAttribute("data-cms-menu");
      var items = (menu && menu[key]) || [];
      var list = host.querySelector("ul");
      if (!list) return;
      list.innerHTML = "";
      items.forEach(function (item) {
        list.appendChild(renderItem(item));
      });
      // Hide the host until we have content — keeps the layout from
      // reserving empty space when there's no menu configured.
      if (items.length === 0) {
        host.setAttribute("hidden", "");
      } else {
        host.removeAttribute("hidden");
      }
    });
    paintBranding(menu);
  }

  // Replaces the inner of every `[data-cms-brand]` host with an <img>
  // when the active theme has a logo configured (resolved by the
  // publisher into menu.branding.logoUrl). The static markup keeps
  // the site title as a text fallback — visible when JS is off, when
  // /data/menu.json is unreachable, or when no logo is configured.
  function paintBranding(menu) {
    var branding = menu && menu.branding;
    var logoUrl = branding && branding.logoUrl;
    if (!logoUrl) return;
    document.querySelectorAll("[data-cms-brand]").forEach(function (host) {
      var alt = host.textContent || "";
      var img = document.createElement("img");
      img.src = logoUrl;
      img.alt = alt;
      img.className = "site-brand__logo";
      img.loading = "lazy";
      host.innerHTML = "";
      host.appendChild(img);
    });
  }

  // Injects a close button (×) into the burger overlay if it isn't already
  // there. We add it via JS so themes can ship the close affordance
  // without having to bake it into the static HTML — saves a full site
  // republish whenever the close UI changes.
  function ensureCloseButton(menu) {
    if (menu.querySelector(".burger-close")) return menu.querySelector(".burger-close");
    var close = document.createElement("button");
    close.type = "button";
    close.className = "burger-close";
    close.setAttribute("aria-label", "Close menu");
    close.innerHTML =
      '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>';
    menu.insertBefore(close, menu.firstChild);
    return close;
  }

  // Inserts a transparent backdrop behind the overlay; clicking it
  // closes the menu. Adding it via JS keeps the static HTML minimal and
  // means the backdrop only exists while the burger feature is active.
  function ensureBackdrop() {
    var existing = document.querySelector(".burger-backdrop");
    if (existing) return existing;
    var backdrop = document.createElement("div");
    backdrop.className = "burger-backdrop";
    backdrop.setAttribute("aria-hidden", "true");
    document.body.appendChild(backdrop);
    return backdrop;
  }

  function wireBurger() {
    var toggle = document.querySelector(".burger-toggle");
    var menu = document.getElementById("burger-menu");
    if (!toggle || !menu) return;

    var close = ensureCloseButton(menu);
    var backdrop = ensureBackdrop();

    function setOpen(open) {
      toggle.setAttribute("aria-expanded", open ? "true" : "false");
      menu.classList.toggle("is-open", open);
      backdrop.classList.toggle("is-open", open);
      document.body.classList.toggle("burger-open", open);
    }

    toggle.addEventListener("click", function () {
      var isOpen = toggle.getAttribute("aria-expanded") === "true";
      setOpen(!isOpen);
    });
    close.addEventListener("click", function () {
      setOpen(false);
    });
    backdrop.addEventListener("click", function () {
      setOpen(false);
    });
    // Close on Escape and on link-tap inside the menu (handy for SPA-feel
    // navigation between pages on mobile).
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") setOpen(false);
    });
    menu.addEventListener("click", function (e) {
      if (e.target.tagName === "A") setOpen(false);
    });
    // Click-outside detector: when the menu is open and the click lands
    // anywhere that's not the menu itself or the toggle, close it.
    // Using `pointerdown` rather than `click` so the close happens before
    // any `click` handler on the underlying element fires (e.g. a link
    // visible behind the overlay).
    document.addEventListener("pointerdown", function (e) {
      if (toggle.getAttribute("aria-expanded") !== "true") return;
      if (menu.contains(e.target)) return;
      if (toggle.contains(e.target)) return;
      setOpen(false);
    });
  }

  function ready(fn) {
    if (document.readyState !== "loading") fn();
    else document.addEventListener("DOMContentLoaded", fn);
  }

  ready(function () {
    wireBurger();
    fetchMenu().then(paint);
  });
})();
